spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: root
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090